name: continuous-integration
on: push

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Set up Ant
        uses: cedx/setup-ant@v5
        with:
          optional-tasks: true
          version: latest
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: lib
          key: java-${{runner.os}}-ivy-${{hashFiles('ivy.xml')}}
          restore-keys: java-${{runner.os}}-ivy-
      - name: Install dependencies
        run: ant install
      - name: Run tests
        run: ant -emacs test
