name: continuous-integration
on: push

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Set up Ant
        uses: cedx/setup-ant@v6
        with:
          optional-tasks: true
          version: latest
      - name: Install dependencies
        run: ant install
      - name: Run tests
        run: ant -emacs test
