author: Cédric Belin
name: Setup Ant
description: Set up your GitHub Actions workflow with a specific version of Apache Ant.

branding:
  color: red
  icon: download

inputs:
  optional-tasks:
    description: Whether to fetch the external libraries required by Ant optional tasks.
    default: false
    required: false
  version:
    description: The version constraint of the Apache Ant binary.
    default: latest
    required: false

runs:
  using: composite
  steps:
    - run: Add-Content $Env:GITHUB_PATH ${{github.action_path}}
      shell: pwsh
    - run: Start.ps1
      shell: pwsh
      env:
        SETUP_ANT_OPTIONAL_TASKS: ${{inputs.optional-tasks}}
        SETUP_ANT_VERSION: ${{inputs.version}}
