name: Setup Ant
description: Set up your GitHub Actions workflow with a specific version of Apache Ant.
author: Cédric Belin

branding:
  color: red
  icon: download

inputs:
  optional-tasks:
    description: Whether to fetch the external libraries required by Ant optional tasks.
    default: false
    required: false
  version:
    description: The version constraint of the Apache Ant binary.
    default: latest
    required: false

runs:
  using: node20
  main: bin/setup_ant.cjs
