# The release data.
export default [
	{version: "1.10.15", archived: no}
	{version: "1.10.14", archived: no}
	{version: "1.10.13", archived: yes}
	{version: "1.10.12", archived: yes}
	{version: "1.10.11", archived: yes}
	{version: "1.10.10", archived: yes}
	{version: "1.10.9", archived: yes}
	{version: "1.10.8", archived: yes}
	{version: "1.10.7", archived: yes}
	{version: "1.10.6", archived: yes}
	{version: "1.10.5", archived: yes}
	{version: "1.10.4", archived: yes}
	{version: "1.10.3", archived: yes}
	{version: "1.10.2", archived: yes}
	{version: "1.10.1", archived: yes}
	{version: "1.10.0", archived: yes}
	{version: "1.9.16", archived: no}
	{version: "1.9.15", archived: yes}
	{version: "1.9.14", archived: yes}
	{version: "1.9.13", archived: yes}
	{version: "1.9.12", archived: yes}
	{version: "1.9.11", archived: yes}
	{version: "1.9.10", archived: yes}
	{version: "1.9.9", archived: yes}
	{version: "1.9.8", archived: yes}
	{version: "1.9.7", archived: yes}
	{version: "1.9.6", archived: yes}
	{version: "1.9.5", archived: yes}
	{version: "1.9.4", archived: yes}
	{version: "1.9.3", archived: yes}
	{version: "1.9.2", archived: yes}
	{version: "1.9.1", archived: yes}
	{version: "1.9.0", archived: yes}
	{version: "1.8.4", archived: yes}
	{version: "1.8.3", archived: yes}
	{version: "1.8.2", archived: yes}
	{version: "1.8.1", archived: yes}
	{version: "1.8.0", archived: yes}
	{version: "1.7.1", archived: yes}
	{version: "1.7.0", archived: yes}
	{version: "1.6.5", archived: yes}
	{version: "1.6.4", archived: yes}
	{version: "1.6.3", archived: yes}
	{version: "1.6.2", archived: yes}
	{version: "1.6.1", archived: yes}
	{version: "1.6.0", archived: yes}
	{version: "1.5.4", archived: yes}
	{version: "1.5.2", archived: yes}
]
