name: continuous-integration
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: node --run test
  run:
    needs: test
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: cedx/setup-ant@main
        with:
          optional-tasks: true
      - run: ant -version
