name: main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  action:
    runs-on: ${{matrix.platform}}
    needs: test
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - uses: cedx/setup-ant@main
        with:
          optional-tasks: true
      - run: ant -version
